---
name: marketplace actions
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "choose the branch to run action against"
        required: true
        default: "test"
env:
  GITHUB_REF: test
jobs:
  repo_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master
      - run: echo $(git branch --show-current)
      - run: echo ${{ env.GITHUB_REF }}
      - run: echo ${{ github.ref }}
  checkout2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_REF == '' && 'master' || env.GITHUB_REF }} 
      - run: echo $(git branch --show-current)
      - run: echo ${{ env.GITHUB_REF }}
      - run: echo ${{ github.ref }}
  rust-toolchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: 1.60.0
      - name: Call rustfmt
        run: rustfmt --edition 2021
