---
name: marketplace actions
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "choose the branch to run action against"
        required: true
        default: "test"

jobs:
  repo_checkout:
    runs-on: ubuntu-latest
    env: 
      GITHUB_REF: ${{ env.GITHUB_REF != '' env.GITHUB_REF && github.event.inputs.branch}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: echo $(git branch --show-current)
  rust-toolchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: 1.60.0
      - name: Call rustfmt
        run: rustfmt --edition 2021
