---
name: Time to shine luv
on:
  workflow_dispatch:
    inputs:
      message:
        description: "say something dirty"
        required: true
        default: "wiscussy"
  pull_request: ~

jobs:
  print-input-based-on-workflow-on-type:
    runs-on: ubuntu-latest
    steps:
      - name: How to detect that you run on PR
        if: "${{ github.event.inputs.message == '' }}"
        run: echo "This is a PR because required input is empty"
      - name: How to detect that you run on manual workflow
        if: "${{ github.event.inputs.message != '' }}"
        run: >
          echo "This is a manual workflow
          because someone send you a message:
          ${{ github.event.inputs.message }}"
      - name: input provided
        if: "${{ github.events.inputs.message != '' }}"
        run: echo "Some one is chatty ${{ github.event.inputs.message }}"
      - name: input is not provided
        if: "${{ github.events.inputs.message == '' }}"
        run: echo "Some one is chatty but has nothing to say"
  run-if-master:
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/master'"
    steps:
      - name: just have some fun
        run: echo "By bitcoin with all my savings!(<|_<|)"
  set-multijob-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: set vars to be used after
        id: set
        run: |
          export "LOL=suck-it-jin-yang"
          echo "::set-output name=lol::${LOL}"
      - name: set branch and wf_run vars
        run: |
          # I know it's meningless to do when you have GitHub context, just f.e.
          branch=$(git branch --show-current)
          echo "::set-output name=branch::${branch}"
    outputs:
      branch: ${{ steps.set.outputs.branch }}
      lol: ${{ steps.set.outputs.lol }}
  get-vars:
    needs: [set-multijob-vars]
    runs-on: ubuntu-latest
    steps:
      - name: print info
        run: |
         echo github.ref ${{ github.ref }}
         echo github.ref == master ${{ github.ref == 'refs/heads/master' }}
         echo ${GITHUB_REF##*/}
      - name: Cancel Previous Runs
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: styfle/cancel-workflow-action@0.9.1
      - name: get var that was set
        run: echo 'Gilfoyle says ${{ needs.set-multijob-vars.outputs.lol }}'
      - name: skip this if output from the job is not expected
        if: ${{ needs.set-multijob-vars.outputs.branch == 'main' }}
        run: echo 'Hey! You finally awake, dragonborn.'
  skip-if-output:
    needs: [set-multijob-vars]
    if: ${{ needs.set-multijob-vars.outputs.branch == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: print output
        run: echo 'Still runnin ${{ needs.set-multijob-vars.outputs.branch }}'
  master-only:
    needs: [skip-if-output]
    steps:
      - name: sup
        run: |
          echo "Aha, here we are on master again"
          echo "So this wf is skipped because of the condition on
          `skip-if-output` job"
  after-all:
    runs-on: ubuntu-latest
    needs: get-vars
    steps:
      - name: end this
        run: echo 'Have mercy'
