name: Time to shine luv 

on: 
  workflow_dispatch:
    inputs:
      message:
        description: "say something dirty"
        required: true
        default: "wiscussy"
  pull_request: ~

jobs:
  give-me-a-chance:
    runs-on: ubuntu-latest
    steps:
      - name: How to detect that you run on PR
        if: "${{ github.event.inputs.message == '' }}"
        run: echo "This is a PR because required input is empty"
      - name: How to detect that you run on manual workflow
        if: "${{ github.event.inputs.message != '' }}"
        run: echo "This is a manual workflow because someone send you a message: ${{ github.event.inputs.message }}"
      - name: Substitute if not provided
        run: echo "${{ github.event.inputs.message || 'don't you want to be friends?..' }}"
