---
name: Time to shine luv
on:
  workflow_dispatch:
    inputs:
      message:
        description: "say something dirty"
        required: true
        default: "wiscussy"
  pull_request: ~

jobs:
  print-input-based-on-workflow-on-type:
    runs-on: ubuntu-latest
    needs: ["wait-for-me"]
    steps:
      - name: How to detect that you run on PR
        if: "${{ github.event.inputs.message == '' }}"
        run: echo "This is a PR because required input is empty"
      - name: How to detect that you run on manual workflow
        if: "${{ github.event.inputs.message != '' }}"
        run: >
          echo "This is a manual workflow
          because someone send you a message:
          ${{ github.event.inputs.message }}"
      - name: input provided
        if: "${{ github.events.inputs.message != '' }}"
        run: echo "Some one is chatty ${{ github.event.inputs.message }}"
      - name: input is not provided
        if: "${{ github.events.inputs.message == '' }}"
        run: echo "Some one is chatty but has nothing to say"
  waits-for-job:
    runs-on: ubuntu-latest
    needs: ["run-if-master"]
    steps:
      - name: Waited
        run: echo 'Now Dobby is free'
  run-if-master:
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/master'"
    steps:
      - name: just have some fun
        run: echo "By bitcoin with all my savings!(<|_<|)"
    outputs:
  set-multijob-vars:
    runs-on: ubuntu-latest
    steps:
      - name: set vars to be used after
        id: set
        run: |
          export "LOL=suck-it-jin-yang"
          echo "::set-output name=lol::${LOL}"
      - name: set branch and wf_run vars
        run: |
          # I know it's meningless to do when you have GitHub context, just f.e.
          branch=$(git branch --show-current)
          echo "::set-output name=branch::${branch}"
    outputs:
      branch: ${{ steps.set.outputs.branch }}
      lol: ${{ steps.set.outputs.lol }}
  get-vars:
    needs: [set-multijob-vars, check-up-to-date]
    runs-on: ubuntu-latest
    steps:
      - name: cancel whole job on condition
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: andymckay/cancel-action@0.2
      - name: get var that was set
        run: echo 'Gilfoyle says ${{ needs.set-multijob-vars.outputs.lol }}'
      - name: skip this if output from the job is not expected
        if: ${{ needs.set-multijob-vars.outputs.branch == 'main' }}
        run: echo 'Hey! You finally awake, dragonborn.'
  after-all:
    runs-on: ubuntu-latest
    needs: get-vars
    steps:
      - name: end this
        run: echo 'Have mercy'
