---
name: Time to shine luv
on:
  workflow_dispatch:
    inputs:
      message:
        description: "say something dirty"
        required: true
        default: "wiscussy"
  pull_request: ~

jobs:
  give-me-a-chance:
    runs-on: ubuntu-latest
    steps:
      - name: How to detect that you run on PR
        if: "${{ github.event.inputs.message == '' }}"
        run: echo "This is a PR because required input is empty"
      - name: How to detect that you run on manual workflow
        if: "${{ github.event.inputs.message != '' }}"
        run: >
          echo "This is a manual workflow
          because someone send you a message:
          ${{ github.event.inputs.message }}"
      - name: input provided
        if: "${{ github.events.inputs.message != '' }}"
        run: echo "Some one is chatty ${{ github.event.inputs.message }}"
      - name: input is not provided
        if: "${{ github.events.inputs.message == '' }}"
        run: echo "Some one is chatty but has nothing to say"
  waits-for-job:
    runs-on: ubuntu-latest
    needs: ["wait-for-me"]
    steps:
      - name: Waited
        run: echo 'Now Dobby is free'
  wait-for-me:
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/master'"
    steps:
      - name: just have some fun
        run: echo "By bitcoin with all my savings!(<|_<|)"
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - name: set var to "1"
        run: SOME_VAR=1 && echo '::set-output name=SOME_VAR::$SOME_VAR'
      - name: dont set var but make output
        run: echo '::set-output name=SOME_VAR2::$SOME_VAR2'
  get-vars:
    needs: set-vars
    runs-on: ubuntu-latest
    steps:
      - name: get var that was set
        run: echo 'This var was set to ${{ steps.main.outputs.SOME_VAR }}'
      - name: get var that was not set
        run: echo 'This var was not set - ${{ steps.main.outputs.SOME_VAR2 }}'
