---
name: update-test
on:
  push:
    branches: [master]
jobs:
  update-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: push
        run: |
          git fetch
          git pull --rebase
          CURRENT=$(git branch --show-current)
          echo Current branch - $CURRENT
          git push origin $CURRENT:test
