---
name: update-test
on:
  push:
    branches: [master]
jobs:
  update-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'commit and push changes'
          push: "origin master:test"
