---
name: update-test
on:
  push:
    branches: [master]
jobs:
  update-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: push
        run: |
          git fetch
          git push origin master:test
